# ===================================================================
# Spring Boot configuration for the "secret-config" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# set System Environment Variables:
# - SPRING_PROFILES_ACTIVE
# - SPRING_DATASOURCE_URL
# - SPRING_DATASOURCE_USERNAME
# - SPRING_LIQUIBASE_URL
# - BASE64_SECRET
# ===================================================================

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ${BASE64_SECRET}
