# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

# spring:
#   datasource:
#     url: jdbc:postgresql://photon.vm:5432/slra_prod
#     username: sis_prod
#     password: prod

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NmE0YTc2ZjE0ZDJkM2M1NjM0ZWEwMDVmN2NiOGE3M2NmZWRkNmMxYTM5OWYzNmQ2ZGY2NTRiMjRhZWYyZjkwNWRhMjFmMmM1M2U3ZGZmYjg4MGQ1YmRmMmE1OWE4NWZmYjY1MzZlN2JhOTVlZDZhMjQyZmY5ZTExYWZkZjcyM2Y=
