# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: SchInfoSys
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDk3MjY0NjJhZTljNWNjNTQ1MzI5MzIxYzRlMDhjZDNjMzZiOWRjZmJjYmY1MTA3MjYwODU1MDQ4ZDRjODQ2N2Y2OGUzMjBjMzEwNDM5MmExMWRlODI5ODY0ZWUwYWM4YTQ4YWM5NTg3YmVkMzZkMzc3NzAxNTIyZTk4Y2I3ZGU=
