package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AcademicTermsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicTermsAllPropertiesEquals(AcademicTerms expected, AcademicTerms actual) {
        assertAcademicTermsAutoGeneratedPropertiesEquals(expected, actual);
        assertAcademicTermsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicTermsAllUpdatablePropertiesEquals(AcademicTerms expected, AcademicTerms actual) {
        assertAcademicTermsUpdatableFieldsEquals(expected, actual);
        assertAcademicTermsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicTermsAutoGeneratedPropertiesEquals(AcademicTerms expected, AcademicTerms actual) {
        assertThat(actual)
            .as("Verify AcademicTerms auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicTermsUpdatableFieldsEquals(AcademicTerms expected, AcademicTerms actual) {
        assertThat(actual)
            .as("Verify AcademicTerms relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getCurrent()).as("check current").isEqualTo(expected.getCurrent()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicTermsUpdatableRelationshipsEquals(AcademicTerms expected, AcademicTerms actual) {
        assertThat(actual)
            .as("Verify AcademicTerms relationships")
            .satisfies(a -> assertThat(a.getYear()).as("check year").isEqualTo(expected.getYear()));
    }
}
