package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AcademicYearAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicYearAllPropertiesEquals(AcademicYear expected, AcademicYear actual) {
        assertAcademicYearAutoGeneratedPropertiesEquals(expected, actual);
        assertAcademicYearAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicYearAllUpdatablePropertiesEquals(AcademicYear expected, AcademicYear actual) {
        assertAcademicYearUpdatableFieldsEquals(expected, actual);
        assertAcademicYearUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicYearAutoGeneratedPropertiesEquals(AcademicYear expected, AcademicYear actual) {
        assertThat(actual)
            .as("Verify AcademicYear auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicYearUpdatableFieldsEquals(AcademicYear expected, AcademicYear actual) {
        assertThat(actual)
            .as("Verify AcademicYear relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getCurrent()).as("check current").isEqualTo(expected.getCurrent()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAcademicYearUpdatableRelationshipsEquals(AcademicYear expected, AcademicYear actual) {
        // empty method
    }
}
