package com.sis.domain;

import static com.sis.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class AccountPayablesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPayablesAllPropertiesEquals(AccountPayables expected, AccountPayables actual) {
        assertAccountPayablesAutoGeneratedPropertiesEquals(expected, actual);
        assertAccountPayablesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPayablesAllUpdatablePropertiesEquals(AccountPayables expected, AccountPayables actual) {
        assertAccountPayablesUpdatableFieldsEquals(expected, actual);
        assertAccountPayablesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPayablesAutoGeneratedPropertiesEquals(AccountPayables expected, AccountPayables actual) {
        assertThat(actual)
            .as("Verify AccountPayables auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPayablesUpdatableFieldsEquals(AccountPayables expected, AccountPayables actual) {
        assertThat(actual)
            .as("Verify AccountPayables relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getPriority()).as("check priority").isEqualTo(expected.getPriority()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAccountPayablesUpdatableRelationshipsEquals(AccountPayables expected, AccountPayables actual) {
        assertThat(actual)
            .as("Verify AccountPayables relationships")
            .satisfies(a -> assertThat(a.getInvoices()).as("check invoices").isEqualTo(expected.getInvoices()))
            .satisfies(a ->
                assertThat(a.getGradeLevelPayables()).as("check gradeLevelPayables").isEqualTo(expected.getGradeLevelPayables())
            );
    }
}
