package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AssessmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentAllPropertiesEquals(Assessment expected, Assessment actual) {
        assertAssessmentAutoGeneratedPropertiesEquals(expected, actual);
        assertAssessmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentAllUpdatablePropertiesEquals(Assessment expected, Assessment actual) {
        assertAssessmentUpdatableFieldsEquals(expected, actual);
        assertAssessmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentAutoGeneratedPropertiesEquals(Assessment expected, Assessment actual) {
        assertThat(actual)
            .as("Verify Assessment auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentUpdatableFieldsEquals(Assessment expected, Assessment actual) {
        assertThat(actual)
            .as("Verify Assessment relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getInstruction()).as("check instruction").isEqualTo(expected.getInstruction()))
            .satisfies(a -> assertThat(a.getMarkScheme()).as("check markScheme").isEqualTo(expected.getMarkScheme()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAssessmentUpdatableRelationshipsEquals(Assessment expected, Assessment actual) {
        assertThat(actual)
            .as("Verify Assessment relationships")
            .satisfies(a -> assertThat(a.getResourceses()).as("check resourceses").isEqualTo(expected.getResourceses()))
            .satisfies(a ->
                assertThat(a.getLearningCompetency()).as("check learningCompetency").isEqualTo(expected.getLearningCompetency())
            );
    }
}
