package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CurriculumMapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumMapAllPropertiesEquals(CurriculumMap expected, CurriculumMap actual) {
        assertCurriculumMapAutoGeneratedPropertiesEquals(expected, actual);
        assertCurriculumMapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumMapAllUpdatablePropertiesEquals(CurriculumMap expected, CurriculumMap actual) {
        assertCurriculumMapUpdatableFieldsEquals(expected, actual);
        assertCurriculumMapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumMapAutoGeneratedPropertiesEquals(CurriculumMap expected, CurriculumMap actual) {
        assertThat(actual)
            .as("Verify CurriculumMap auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumMapUpdatableFieldsEquals(CurriculumMap expected, CurriculumMap actual) {
        assertThat(actual)
            .as("Verify CurriculumMap relevant properties")
            .satisfies(a -> assertThat(a.getQuarterNo()).as("check quarterNo").isEqualTo(expected.getQuarterNo()))
            .satisfies(a -> assertThat(a.getWeekNo()).as("check weekNo").isEqualTo(expected.getWeekNo()))
            .satisfies(a -> assertThat(a.getTopic()).as("check topic").isEqualTo(expected.getTopic()))
            .satisfies(a -> assertThat(a.getContentStandards()).as("check contentStandards").isEqualTo(expected.getContentStandards()))
            .satisfies(a ->
                assertThat(a.getPerformanceStandards()).as("check performanceStandards").isEqualTo(expected.getPerformanceStandards())
            )
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCurriculumMapUpdatableRelationshipsEquals(CurriculumMap expected, CurriculumMap actual) {
        assertThat(actual)
            .as("Verify CurriculumMap relationships")
            .satisfies(a -> assertThat(a.getCourse()).as("check course").isEqualTo(expected.getCourse()));
    }
}
