package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class GradeLevelPayablesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeLevelPayablesAllPropertiesEquals(GradeLevelPayables expected, GradeLevelPayables actual) {
        assertGradeLevelPayablesAutoGeneratedPropertiesEquals(expected, actual);
        assertGradeLevelPayablesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeLevelPayablesAllUpdatablePropertiesEquals(GradeLevelPayables expected, GradeLevelPayables actual) {
        assertGradeLevelPayablesUpdatableFieldsEquals(expected, actual);
        assertGradeLevelPayablesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeLevelPayablesAutoGeneratedPropertiesEquals(GradeLevelPayables expected, GradeLevelPayables actual) {
        assertThat(actual)
            .as("Verify GradeLevelPayables auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeLevelPayablesUpdatableFieldsEquals(GradeLevelPayables expected, GradeLevelPayables actual) {
        assertThat(actual)
            .as("Verify GradeLevelPayables relevant properties")
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertGradeLevelPayablesUpdatableRelationshipsEquals(GradeLevelPayables expected, GradeLevelPayables actual) {
        assertThat(actual)
            .as("Verify GradeLevelPayables relationships")
            .satisfies(a -> assertThat(a.getGradelevel()).as("check gradelevel").isEqualTo(expected.getGradelevel()));
    }
}
