package com.sis.domain;

import static com.sis.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class InvoicesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoicesAllPropertiesEquals(Invoices expected, Invoices actual) {
        assertInvoicesAutoGeneratedPropertiesEquals(expected, actual);
        assertInvoicesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoicesAllUpdatablePropertiesEquals(Invoices expected, Invoices actual) {
        assertInvoicesUpdatableFieldsEquals(expected, actual);
        assertInvoicesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoicesAutoGeneratedPropertiesEquals(Invoices expected, Invoices actual) {
        assertThat(actual)
            .as("Verify Invoices auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoicesUpdatableFieldsEquals(Invoices expected, Invoices actual) {
        assertThat(actual)
            .as("Verify Invoices relevant properties")
            .satisfies(a -> assertThat(a.getDueDate()).as("check dueDate").isEqualTo(expected.getDueDate()))
            .satisfies(a ->
                assertThat(a.getAmountPaid())
                    .as("check amountPaid")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAmountPaid())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInvoicesUpdatableRelationshipsEquals(Invoices expected, Invoices actual) {
        assertThat(actual)
            .as("Verify Invoices relationships")
            .satisfies(a -> assertThat(a.getStudent()).as("check student").isEqualTo(expected.getStudent()));
    }
}
