package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LearningCompetencyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetencyAllPropertiesEquals(LearningCompetency expected, LearningCompetency actual) {
        assertLearningCompetencyAutoGeneratedPropertiesEquals(expected, actual);
        assertLearningCompetencyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetencyAllUpdatablePropertiesEquals(LearningCompetency expected, LearningCompetency actual) {
        assertLearningCompetencyUpdatableFieldsEquals(expected, actual);
        assertLearningCompetencyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetencyAutoGeneratedPropertiesEquals(LearningCompetency expected, LearningCompetency actual) {
        assertThat(actual)
            .as("Verify LearningCompetency auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetencyUpdatableFieldsEquals(LearningCompetency expected, LearningCompetency actual) {
        assertThat(actual)
            .as("Verify LearningCompetency relevant properties")
            .satisfies(a -> assertThat(a.getSeqNo()).as("check seqNo").isEqualTo(expected.getSeqNo()))
            .satisfies(a -> assertThat(a.getCompetencyCode()).as("check competencyCode").isEqualTo(expected.getCompetencyCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLearningCompetencyUpdatableRelationshipsEquals(LearningCompetency expected, LearningCompetency actual) {
        assertThat(actual)
            .as("Verify LearningCompetency relationships")
            .satisfies(a -> assertThat(a.getCurriculumMap()).as("check curriculumMap").isEqualTo(expected.getCurriculumMap()));
    }
}
