package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResourcesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcesAllPropertiesEquals(Resources expected, Resources actual) {
        assertResourcesAutoGeneratedPropertiesEquals(expected, actual);
        assertResourcesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcesAllUpdatablePropertiesEquals(Resources expected, Resources actual) {
        assertResourcesUpdatableFieldsEquals(expected, actual);
        assertResourcesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcesAutoGeneratedPropertiesEquals(Resources expected, Resources actual) {
        assertThat(actual)
            .as("Verify Resources auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcesUpdatableFieldsEquals(Resources expected, Resources actual) {
        assertThat(actual)
            .as("Verify Resources relevant properties")
            .satisfies(a -> assertThat(a.getFileName()).as("check fileName").isEqualTo(expected.getFileName()))
            .satisfies(a -> assertThat(a.getDocument()).as("check document").isEqualTo(expected.getDocument()))
            .satisfies(a ->
                assertThat(a.getDocumentContentType()).as("check document content type").isEqualTo(expected.getDocumentContentType())
            )
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResourcesUpdatableRelationshipsEquals(Resources expected, Resources actual) {
        assertThat(actual)
            .as("Verify Resources relationships")
            .satisfies(a -> assertThat(a.getStrategieses()).as("check strategieses").isEqualTo(expected.getStrategieses()))
            .satisfies(a -> assertThat(a.getAssessments()).as("check assessments").isEqualTo(expected.getAssessments()));
    }
}
