package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StrategiesAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrategiesAllPropertiesEquals(Strategies expected, Strategies actual) {
        assertStrategiesAutoGeneratedPropertiesEquals(expected, actual);
        assertStrategiesAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrategiesAllUpdatablePropertiesEquals(Strategies expected, Strategies actual) {
        assertStrategiesUpdatableFieldsEquals(expected, actual);
        assertStrategiesUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrategiesAutoGeneratedPropertiesEquals(Strategies expected, Strategies actual) {
        assertThat(actual)
            .as("Verify Strategies auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrategiesUpdatableFieldsEquals(Strategies expected, Strategies actual) {
        assertThat(actual)
            .as("Verify Strategies relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStrategiesUpdatableRelationshipsEquals(Strategies expected, Strategies actual) {
        assertThat(actual)
            .as("Verify Strategies relationships")
            .satisfies(a -> assertThat(a.getResourceses()).as("check resourceses").isEqualTo(expected.getResourceses()))
            .satisfies(a ->
                assertThat(a.getLearningCompetency()).as("check learningCompetency").isEqualTo(expected.getLearningCompetency())
            );
    }
}
