package com.sis.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAllPropertiesEquals(Student expected, Student actual) {
        assertStudentAutoGeneratedPropertiesEquals(expected, actual);
        assertStudentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAllUpdatablePropertiesEquals(Student expected, Student actual) {
        assertStudentUpdatableFieldsEquals(expected, actual);
        assertStudentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentAutoGeneratedPropertiesEquals(Student expected, Student actual) {
        assertThat(actual)
            .as("Verify Student auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentUpdatableFieldsEquals(Student expected, Student actual) {
        assertThat(actual)
            .as("Verify Student relevant properties")
            .satisfies(a -> assertThat(a.getLrn()).as("check lrn").isEqualTo(expected.getLrn()))
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getMiddleName()).as("check middleName").isEqualTo(expected.getMiddleName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getExtName()).as("check extName").isEqualTo(expected.getExtName()))
            .satisfies(a -> assertThat(a.getEnrollmentDate()).as("check enrollmentDate").isEqualTo(expected.getEnrollmentDate()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()))
            .satisfies(a -> assertThat(a.getBirthPlace()).as("check birthPlace").isEqualTo(expected.getBirthPlace()))
            .satisfies(a -> assertThat(a.getContactNo()).as("check contactNo").isEqualTo(expected.getContactNo()))
            .satisfies(a -> assertThat(a.getAddress1()).as("check address1").isEqualTo(expected.getAddress1()))
            .satisfies(a -> assertThat(a.getAddress2()).as("check address2").isEqualTo(expected.getAddress2()))
            .satisfies(a -> assertThat(a.getCity()).as("check city").isEqualTo(expected.getCity()))
            .satisfies(a -> assertThat(a.getZipCode()).as("check zipCode").isEqualTo(expected.getZipCode()))
            .satisfies(a -> assertThat(a.getCountry()).as("check country").isEqualTo(expected.getCountry()))
            .satisfies(a -> assertThat(a.getNationality()).as("check nationality").isEqualTo(expected.getNationality()))
            .satisfies(a -> assertThat(a.getMotherTongue()).as("check motherTongue").isEqualTo(expected.getMotherTongue()))
            .satisfies(a -> assertThat(a.getReligion()).as("check religion").isEqualTo(expected.getReligion()))
            .satisfies(a -> assertThat(a.getFathersLastName()).as("check fathersLastName").isEqualTo(expected.getFathersLastName()))
            .satisfies(a -> assertThat(a.getFathersMiddleName()).as("check fathersMiddleName").isEqualTo(expected.getFathersMiddleName()))
            .satisfies(a -> assertThat(a.getFathersFirstName()).as("check fathersFirstName").isEqualTo(expected.getFathersFirstName()))
            .satisfies(a -> assertThat(a.getFathersExtName()).as("check fathersExtName").isEqualTo(expected.getFathersExtName()))
            .satisfies(a -> assertThat(a.getFathersOccupation()).as("check fathersOccupation").isEqualTo(expected.getFathersOccupation()))
            .satisfies(a -> assertThat(a.getFathersContacts()).as("check fathersContacts").isEqualTo(expected.getFathersContacts()))
            .satisfies(a -> assertThat(a.getMothersLastName()).as("check mothersLastName").isEqualTo(expected.getMothersLastName()))
            .satisfies(a -> assertThat(a.getMothersMiddleName()).as("check mothersMiddleName").isEqualTo(expected.getMothersMiddleName()))
            .satisfies(a -> assertThat(a.getMothersFirstName()).as("check mothersFirstName").isEqualTo(expected.getMothersFirstName()))
            .satisfies(a -> assertThat(a.getMothersOccupation()).as("check mothersOccupation").isEqualTo(expected.getMothersOccupation()))
            .satisfies(a -> assertThat(a.getMothersContacts()).as("check mothersContacts").isEqualTo(expected.getMothersContacts()))
            .satisfies(a -> assertThat(a.getGuardianFullName()).as("check guardianFullName").isEqualTo(expected.getGuardianFullName()))
            .satisfies(a -> assertThat(a.getGuardianContacts()).as("check guardianContacts").isEqualTo(expected.getGuardianContacts()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStudentUpdatableRelationshipsEquals(Student expected, Student actual) {
        assertThat(actual)
            .as("Verify Student relationships")
            .satisfies(a -> assertThat(a.getGender()).as("check gender").isEqualTo(expected.getGender()))
            .satisfies(a -> assertThat(a.getCourseSchedules()).as("check courseSchedules").isEqualTo(expected.getCourseSchedules()));
    }
}
